### ISSUE TITLE
SMTP connection failures

### ISSUE THREAD

**Issue by lreneral** [tum-gis/sddi-ckan-k8s#4] opened 2023-06-09 16:06 UTC
### What happened?

my smtp configuration doesnt work. I have used the smtp configuration of ionos (See details in the configuraiton setting). I tried the "forgotten password?" but the email wasnt send (see below the log of the ckan's pod)

### Steps to reproduce

1. Deploy HelmCharts with SMTP Configuration
2. Create a User with email
3. Test the "Password Forgotten?", The email doesnt come.

### Configuration

```YAML
ckan:
 smtp:
    # -- [CKAN SMTP settings](https://docs.ckan.org/en/latest/maintaining/configuration.html#email-settings)
    server: "smtp.ionos.de:587" or "smtp.ionos.de:465"
    # -- [CKAN SMTP settings](https://docs.ckan.org/en/latest/maintaining/configuration.html#email-settings)
    user: "******"
    # -- [CKAN SMTP settings](https://docs.ckan.org/en/latest/maintaining/configuration.html#email-settings)
    password: "**********"
    # -- [CKAN SMTP settings](https://docs.ckan.org/en/latest/maintaining/configuration.html#email-settings)
    mailFrom: "admin@********"
    # -- [CKAN SMTP settings](https://docs.ckan.org/en/latest/maintaining/configuration.html#email-settings)
    tls: "enable"
    # -- [CKAN SMTP settings](https://docs.ckan.org/en/latest/maintaining/configuration.html#email-settings)
    startTls: "true"
    # -- [CKAN SMTP settings](https://docs.ckan.org/en/latest/maintaining/configuration.html#email-settings)
    replyTo: "None"
```

#### Version information
- helm version: version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}
- Kubernetes: v1.25.2-r0

#### Environment information
- VARIABLE_NAME: `values`

### Relevant log output

```Shell
**LOGS CKAN**

[ckan.views.user] Password reset requested for user "********@******.de"
2023-06-09 15:42:30,607 INFO  [ckan.views.user] Emailing reset link to user: nsoule
2023-06-09 15:42:30,705 ERROR [ckan.config.middleware.flask_app] Server not connected
Traceback (most recent call last):
  File "/srv/app/src/ckan/ckan/lib/mailer.py", line 96, in _mail_recipient
    smtp_connection.starttls()
  File "/usr/lib/python3.8/smtplib.py", line 788, in starttls
    self.sock = context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/site-packages/gevent/_ssl3.py", line 114, in wrap_socket
    return self.sslsocket_class(
  File "/usr/lib/python3.8/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/lib/python3.8/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/lib/python3.8/site-packages/gevent/_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:1131)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/srv/app/src/ckan/ckan/config/middleware/../../views/user.py", line 662, in post
    mailer.send_reset_link(user_obj)
  File "/srv/app/src/ckan/ckan/lib/mailer.py", line 188, in send_reset_link
    mail_user(user, subject, body)
  File "/srv/app/src/ckan/ckan/lib/mailer.py", line 133, in mail_user
    mail_recipient(recipient.display_name, recipient.email, subject,
  File "/srv/app/src/ckan/ckan/lib/mailer.py", line 124, in mail_recipient
    return _mail_recipient(recipient_name, recipient_email,
  File "/srv/app/src/ckan/ckan/lib/mailer.py", line 116, in _mail_recipient
    smtp_connection.quit()
  File "/usr/lib/python3.8/smtplib.py", line 1002, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.8/smtplib.py", line 429, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.8/smtplib.py", line 376, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.8/smtplib.py", line 361, in send
    raise SMTPServerDisconnected('Server not connected')
```

**Comment by BWibo** [comment] 2023-06-12 07:23
Hey there, thx for reporting this. Two questions:
- Which version of the helm chart and the sddi-ckan docker image are you using? I need the exact versions to reproduces this.
- Are you running this in a local testing environment with self-signed SSL certificates of with a FQDN and proper SSL? The log messge you posted suggest that this might be related to SSL.
   ```
   ssl.SSLError: [SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:1131)
   ```

**Comment by BWibo** [comment] 2023-06-12 11:53
While doing some testing with SMTP I found an issue regarding the smtp options, see here:
tum-gis/sddi-ckan-k8s#5

The `ckan.smtp.tls` option is not used and should be removed. As the option is not used at all, this should not affect this issue.

**Comment by BWibo** [comment] 2023-06-12 15:01
I just did some testing with different eMail providers on an instance with a **FQDN** and **SSL certificates from Let's Encrypt**. 
Indeed, there seems to be a problem with SMTP. Depending on the provider I tested and settings I used I got working or not.
I tried gmx.de, one.com and united-domains.de with different settings for TLS and STARTTLS.

The SSL error listed in your logs never happend to me.

The configuration that worked with 2/3 providers was with STARTTLS enabled and the according port (587) set.

```yml
ckan:
  smtp:
    server: "my.smtp.de:587"
    user: "******"
    password: "**********"
    mailFrom: "the@********"
    startTls: "True"
    replyTo: "None"
 ```

This leads me to the assuption that this is a CKAN internal error and not related to the helm chart itself.

**Comment by lreneral** [comment] 2023-06-14 10:24
We are waiting for a reply with a fixed version of SDDI (with fixes made to CKAN) which we can deploy and test. We used the base version of SDDI HELM Chart and used the relevant configuration for SMTP. Since it does not doesnt work, we can not use it with the deployment for further byte projects.

Docker version of ckan: ghcr.io/tum-gis/ckan-sddi:0.0.4
Yes we have an SSL Certificate and FQDN

**Comment by BWibo** [comment] 2023-06-14 12:12
1. As you can read above, your inital issue submission was incomplete. I was and still am waiting for essential version information, as you can read [here](https://github.com/tum-gis/sddi-ckan-k8s/issues/4#issuecomment-1586737072). Without this information I am unable to help you, because it is impossible to reproduce your problem. Your last post, partially provides this information. Now I know the version of the Docker image, but I'm still missing the **version of the Helm chart** you are using. If you need assistance in finding that version information let me know, I can help.

   I updated the issue form to avoid this kind of problem in the future. Take look at the new form
   [here](https://github.com/tum-gis/sddi-ckan-k8s/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml). It contains some hints on how to find version info now.

2. The version of the docker image you are using is outdated and a pre-release version, too. As you can see in [ckan-docker releases](https://github.com/tum-gis/ckan-docker/releases), the most recent version is `v1.0.1`. I recommend watching the [tum-gis/ckan-docker](https://github.com/tum-gis/ckan-docker) and [tum-gis/sddi-ckan-k8s](https://github.com/tum-gis/sddi-ckan-k8s) to stay tuned for new releases.
Please repeat your testing with the most recent version.

3. I am not a CKAN core developer. It is neither my responsibility nor am I capable of fixing issues of the CKAN core application. If it turns out, that this is a general problem of CKAN, we need to file an issue [here](https://github.com/ckan/ckan/issues).

**Comment by BWibo** [comment] 2023-06-16 08:40
One more thing:
Using the debug image (`ghcr.io/tum-gis/ckan-sddi:1.0.1-debug`), you can verify if the credentials are correctly mapped to CKAN. Please check if this is the case. A possible issue could be special chars in e.g. in the password, that corrupt the string during variable expansion.

![grafik](https://github.com/tum-gis/sddi-ckan-k8s/assets/7643434/a9159f0c-ce4b-4cbc-ab74-e686bf182047)

**Comment by BWibo** [comment] 2023-06-20 16:20
@lreneral: I did some more testing with the test account you provided and I got it working. I just omitted the port. If found this by trail and error... This is not very well documented in the CKAN docs.

Todo:
- [ ] Improve smtp settings documentation in the Helm chart

This is the config that worked for me:

```yml
ckan:
  smtp:
    server: "smtp.ionos.de"
    user: "secret"
    password: "secret"
    mailFrom: "me@abc.de"
    startTls: "True"
    replyTo: "me@abc.de"
```
We're are currently doing some more testing, to if this works for other providers too.

**Comment by BWibo** [comment] 2023-06-21 09:06
I did some more testing and found that the configuration above works for all test providers I used.
I updated the documentation in #7 and files an issue in the CKAN main repo to improve the documentation (ckan/ckan/issues/7666).

Closing, as this should work for all providers. Please reopen if more problem come up related to this.

**Closed by BWibo** 2023-06-21 09:06 UTC
Labels: state: feedback required

**Comment by lreneral** [comment] 2023-06-26 09:56
@BWibo Thanks! It worked without the port as well from my side.
